# NumPy

## Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of `numpy`, a powerful package to do data science.\
A list `baseball` has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a `numpy` array from it?

- Import the `numpy` package as `np`, so that you can refer to numpy with np.
- Use `np.array()` to create a `numpy` array from `baseball`. Name this array np_baseball.
- Print out the type of `np_baseball` to check that you got it right.

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


## Baseball players' height

You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: `height_in`. The height is expressed in inches. Can you make a `numpy` array out of it and convert the units to meters?

`height_in` is already available and the `numpy` package is loaded, so you can start straight away (Source: stat.ucla.edu).

In [2]:
import pandas as pd
import numpy as np
baseball = pd.read_csv('datasets/baseball.csv')
baseball.head()

Name Team       Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL        Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL        Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL        Catcher      72     210  30.78     Catcher
3     Kevin_Millar  BAL  First_Baseman      72     210  35.43   Infielder
4      Chris_Gomez  BAL  First_Baseman      73     188  35.71   Infielder

### Instructions
- Create a `numpy` array from `height_in`. Name this new array `np_height_in`.
- Print `np_height_in`.
- Multiply `np_height_in` with `0.0254` to convert all height measurements from inches to meters. Store the new values in a new array, `np_height_m`.
- Print out `np_height_m` and check if the output makes sense.

In [3]:
height_in = baseball['Height'].values
height_in

array([74, 74, 72, ..., 75, 75, 73])

In [4]:
np_height_in = np.array(height_in)
print(np_height_in)

[74 74 72 ... 75 75 73]


In [5]:
np_height_m = np_height_in*0.0254
print(np_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


## Baseball player's BMI

The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: `height_in` and `weight_lb`. `height_in` is in inches and `weight_lb` is in pounds.

It's now possible to calculate the BMI of each baseball player. Python code to convert `height_in` to a numpy array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game!

In [6]:
weight_lb = baseball['Weight'].values
weight_lb

array([180, 215, 210, ..., 205, 190, 195])

### Instructions
- Create a `numpy` array from the `weight_lb` list with the correct units. Multiply by `0.453592` to go from pounds to kilograms. Store the resulting `numpy` array as `np_weight_kg`.
- Use `np_height_m` and `np_weight_kg` to calculate the BMI of each player. Use the following equation:

\begin{equation}
BMI = \frac{weight(kg)}{height(m)^2}
\end{equation}

    Save the resulting numpy array as bmi.
- Print out `bmi`

In [7]:
np_weight_kg = np.array(weight_lb)*0.453592
np_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [8]:
bmi = np_weight_kg/np_height_m**2
bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

## Lightweight baseball players

To subset both regular Python lists and numpy arrays, you can use square brackets:
```
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]
```
For `numpy` specifically, you can also use boolean `numpy` arrays:
```
high = y > 5
y[high]
```
The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data!

### Instructions
- Create a boolean `numpy` array: the element of the array should be `True` if the corresponding baseball player's BMI is below `21`. You can use the `<` operator for this. Name the array `light`.
- Print the array `light`.
- Print out a `numpy` array with the BMIs of all baseball players whose BMI is below 21. Use `light` inside square brackets to do a selection on the `bmi` array.

In [9]:
light = bmi < 21
light

array([False, False, False, ..., False, False, False])

In [10]:
bmi[light]

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

## Subsetting NumPy Arrays

You've seen it with your own eyes: Python lists and `numpy` arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the IPython Shell:
```
x = ["a", "b", "c"]
x[1]
```
```
np_x = np.array(x)
np_x[1]
```
The script in the editor already contains code that imports `numpy` as `np`, and stores both the height and weight of the MLB players as `numpy` arrays.

### Instructions
- Subset `np_weight_lb` by printing out the element at index 50.
- Print out a sub-array of `np_height_in` that contains the elements at index 100 up to and including index 110.

In [11]:
np_weight_lb = np.array(weight_lb)
print(np_weight_lb[50])

200


In [12]:
print(np_height_in[100:111])

[73 74 72 73 69 72 73 75 75 73 72]


## Your First 2D NumPy Array

Before working on the actual MLB data, let's try to create a 2D `numpy` array from a small list of lists.

In this exercise, `baseball` is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 `baseball` players, in this order. baseball is already coded for you in the script.

## Instructions
- Use `np.array()` to create a 2D numpy array from `baseball`. Name it `np_baseball`.
- Print out the `type`
 of `np_baseball`.
- Print out the shape attribute of `np_baseball`. Use `np_baseball.shape`.

In [13]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

np_baseball = np.array(baseball)

print(type(np_baseball))
print(np_baseball.shape)


<class 'numpy.ndarray'>
(4, 2)


## Baseball data in 2D form

You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D numpy array. This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).

The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is baseball.

Can you store the data as a 2D array to unlock numpy's extra functionality?

### Instructions
- Use `np.array()` to create a 2D numpy array from baseball. Name it `np_baseball`.
- Print out the `shape` attribute of `np_baseball`.

In [14]:
baseball_df = pd.read_csv('datasets/baseball.csv')
baseball = baseball_df[['Height','Weight']].to_numpy()


In [15]:
baseball_df = pd.read_csv('datasets/baseball.csv')
baseball = baseball_df[['Height','Weight']].to_numpy()

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1015, 2)


## Subsetting 2D NumPy Arrays

If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements `"a"` and `"c"` are extracted from a list of lists.
```Python
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]
```
For regular Python lists, this is a real pain. For 2D numpy arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.

The code that converts the pre-loaded `baseball` list to a 2D numpy array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 

## Instructions
- Print out the 50th row of `np_baseball`.
- Make a new variable, `np_weight_lb`, containing the entire second column of `np_baseball`.
- Select the height (first column) of the 124th baseball player in `np_baseball` and print it out.

In [16]:
np_baseball[49]

array([ 70, 195])

In [17]:
np_weight_lb = np_baseball[:,1]

In [18]:
np_baseball[123,0]

75

## 2D Arithmetic

Remember how you calculated the Body Mass Index for all baseball players? numpy was able to perform all calculations element-wise (i.e. element by element). For 2D numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

Execute the code below in the IPython shell and see if you understand:
```Python
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat
```
`np_baseball` is coded for you; it's again a 2D numpy array with 3 columns representing height (in inches), weight (in pounds) and age (in years).

### Instructions
- You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add `np_baseball`.
- You want to convert the units of height and weight to metric (meters and kilograms respectively). As a first step, create a numpy array with three values: `0.0254`, `0.453592` and `1`. Name this array `conversion`.
- Multiply `np_baseball` with `conversion` and print out the result.

In [19]:
baseball_df = pd.read_csv('datasets/baseball.csv')
np_baseball = baseball_df[['Height','Weight','Age']].to_numpy()
np_baseball

array([[ 74.  , 180.  ,  22.99],
       [ 74.  , 215.  ,  34.69],
       [ 72.  , 210.  ,  30.78],
       ...,
       [ 75.  , 205.  ,  25.19],
       [ 75.  , 190.  ,  31.01],
       [ 73.  , 195.  ,  27.92]])

In [20]:
conversion=[0.0254,0.453592,1]

In [21]:
np_baseball = np_baseball*conversion
np_baseball

array([[ 1.8796 , 81.64656, 22.99   ],
       [ 1.8796 , 97.52228, 34.69   ],
       [ 1.8288 , 95.25432, 30.78   ],
       ...,
       [ 1.905  , 92.98636, 25.19   ],
       [ 1.905  , 86.18248, 31.01   ],
       [ 1.8542 , 88.45044, 27.92   ]])

## Average versus median

You now know how to use numpy functions to get a better feeling for your data. It basically comes down to importing numpy and then calling several simple functions on the numpy arrays:
```Python
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)
np.median(x)
```
The baseball data is available as a 2D numpy array with 3 columns (height, weight, age) and 1015 rows. The name of this numpy array is `np_baseball`. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers.

### Instructions
- Create numpy array `np_height_in` that is equal to first column of `np_baseball`.
- Print out the mean of `np_height_in`.
- Print out the median of `np_height_in`.

In [22]:
baseball_df = pd.read_csv('datasets/baseball.csv')
np_baseball = baseball_df[['Height','Weight']].to_numpy()
np_height_in = np_baseball[:,0]

In [23]:
np.mean(np_height_in)

73.6896551724138

In [24]:
np.median(np_height_in)

74.0

## Explore the baseball data

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array `np_baseball`, with three columns. The Python script in the editor already includes code to print out informative messages with the different summary statistics. Can you finish the job?

### Instructions
- The code to print out the mean height is already included. Complete the code for the median height. Replace `None` with the correct code.
- Use `np.std()` on the first column of `np_baseball` to calculate `stddev`. Replace `None` with the correct code.
- Do big players tend to be heavier? Use `np.corrcoef()` to store the correlation between the first and second column of `np_baseball` in `corr`. Replace None with the correct code.

In [25]:
avg = np.mean(np_baseball[:,0])
print('The average: ' + str(avg))

The average: 73.6896551724138


In [26]:
med = np.mean(np_baseball[:,0])
print('Median: ' + str(med))

Median: 73.6896551724138


In [27]:
stddev = np.std(np_baseball[:,0])
print('Standard Deviation: ' + str(stddev))

Standard Deviation: 2.312791881046546


In [28]:
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print('Correlation: ' + str(corr))

Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


## Blend it all together

In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:
```Python
positions = ['GK', 'M', 'A', 'D', ...]
heights = [191, 184, 185, 180, ...]
```
Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's `position`. The possible positions are: `'GK'` (goalkeeper), `'M'` (midfield), `'A'` (attack) and `'D'` (defense). The second list, `heights`, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

### Instructions
- Convert `heights` and `positions`, which are regular lists, to numpy arrays. Call them `np_heights` and `np_positions`.
- Extract all the heights of the goalkeepers. You can use a little trick here: use `np_positions == 'GK'` as an index for `np_heights`. Assign the result to `gk_heights`.
- Extract all the heights of all the other players. This time use `np_positions != 'GK'` as an index for `np_heights`. Assign the result to `other_heights`.
- Print out the median height of the goalkeepers using `np.median()`. Replace `None` with the correct code.
- Do the same for the other players. Print out their median height. Replace `None` with the correct code.

In [86]:
fifa = pd.read_csv('datasets/fifa.csv') # CSV columns name contains spaces (nice to know -_-)
fifa.columns = fifa.columns.str.replace(' ','') # Remove spaces from columns name
fifa['position']=fifa['position'].str.replace(' ','') # Remove spaces from column 'position'
fifa.head(2)

id           name  rating position  height    foot  rare pace shooting  \
0    1001   Gábor Király      69       GK     191   Right     0                 
1  100143   Frederik Boi      65        M     184   Right     0   61       65   

  passing dribbling defending heading diving handling kicking reflexes speed  \
0                                         70       66      63       74    35   
1      63        59        62      62                                          

   positioning  
0         66.0  
1          NaN

In [85]:
np_positions = fifa[['position']].to_numpy()
np_positions

array([['GK'],
       ['M'],
       ['A'],
       ...,
       ['D'],
       ['D'],
       ['M']], dtype=object)

In [62]:
np_heights = fifa[['height']].to_numpy()
np_heights

array([[191],
       [184],
       [185],
       ...,
       [183],
       [179],
       [179]])

In [87]:
gk_heights = np_heights[np_positions == 'GK']

In [88]:
other_heights = np_heights[np_positions != 'GK']

In [89]:
np.median(gk_heights)

188.0

In [90]:
np.median(other_heights)

181.0